cloud:
  aws:
    region:
      static: ap-southeast-1
      auto: false
    credentials:
      access-key:AKIAQ4NSA2SCP635OF3B
      secret-key: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
    end-point:
      uri:https://sqs.ap-southeast-1.amazonaws.com/061039760516/BetterWellnessMsg.fifo